name: Git Version

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'


jobs:
  Versioning:
    outputs:
      version: ${{ steps.version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Generate version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main

      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}

      - name: Create the tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.version.outputs.VERSION }}
